import { Project, Theme } from '../types';

// These URLs represent static assets generated by our Flux pipeline.
const ASSETS = {
  LEO: {
    P1: "https://image.pollinations.ai/prompt/cute%203d%20cartoon%20pixar%20style%2C%20Leo%20a%20young%20boy%20with%20curly%20blonde%20hair%20and%20blue%20eyes%20wearing%20a%20silver%20space%20helmet%2C%20sitting%20in%20a%20cardboard%20box%20spaceship%20in%20his%20bedroom%2C%20night%20time%2C%20cozy%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=42",
    P2: "https://image.pollinations.ai/prompt/cute%203d%20cartoon%20pixar%20style%2C%20Leo%20a%20young%20boy%20with%20curly%20blonde%20hair%20floating%20in%20zero%20gravity%20inside%20a%20spaceship%2C%20looking%20out%20the%20window%20at%20colorful%20planets%2C%20outer%20space%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=123",
    P3: "https://image.pollinations.ai/prompt/cute%203d%20cartoon%20pixar%20style%2C%20Leo%20blonde%20hair%20looking%20surprised%20as%20a%20cute%20three-eyed%20purple%20alien%20taps%20on%20the%20spaceship%20window%2C%20background%20space%20stars%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=789",
    P4: "https://image.pollinations.ai/prompt/cute%203d%20cartoon%20pixar%20style%2C%20Leo%20blonde%20hair%20piloting%20spaceship%20using%20a%20joystick%2C%20outside%20view%20shows%20a%20yo-yo%20grappling%20hook%20catching%20a%20yellow%20moon%20made%20of%20cheese%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=555",
    P5: "https://image.pollinations.ai/prompt/cute%203d%20cartoon%20pixar%20style%2C%20Leo%20blonde%20hair%20waving%20goodbye%20to%20purple%20alien%20Blip%2C%20Leo%20holding%20basket%20of%20glowing%20berries%2C%20earth%20visible%20in%20distance%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=999",
    P6: "https://image.pollinations.ai/prompt/cute%203d%20cartoon%20pixar%20style%2C%20Leo%20blonde%20hair%20sleeping%20peacefully%20in%20his%20bed%2C%20cardboard%20box%20spaceship%20next%20to%20him%2C%20moonlight%20shines%20in%20through%20window%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=333"
  },
  MAYA: {
    P1: "https://image.pollinations.ai/prompt/soft%20dreamy%20watercolor%20painting%2C%20Maya%20a%20little%20girl%20with%20dark%20brown%20pigtails%20and%20brown%20eyes%20opening%20a%20wooden%20garden%20gate%2C%20lush%20green%20garden%2C%20magical%20atmosphere%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=111",
    P2: "https://image.pollinations.ai/prompt/soft%20dreamy%20watercolor%20painting%2C%20Maya%20brown%20pigtails%20kneeling%20at%20base%20of%20large%20oak%20tree%2C%20looking%20closely%20at%20tiny%20magical%20wooden%20door%20carved%20in%20bark%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=222",
    P3: "https://image.pollinations.ai/prompt/soft%20dreamy%20watercolor%20painting%2C%20cute%20squirrel%20wearing%20a%20monocle%20holding%20a%20sunflower%20seed%20watch%2C%20standing%20next%20to%20Maya%20brown%20pigtails%2C%20magical%20forest%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=333",
    P4: "https://image.pollinations.ai/prompt/soft%20dreamy%20watercolor%20painting%2C%20Maya%20brown%20pigtails%20running%20through%20magical%20forest%20holding%20squirrel%2C%20sunlight%20filtering%20through%20leaves%2C%20dynamic%20action%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=444",
    P5: "https://image.pollinations.ai/prompt/soft%20dreamy%20watercolor%20painting%2C%20Maya%20brown%20pigtails%20standing%20in%20forest%20clearing%20surrounded%20by%20glowing%20fireflies%20and%20happy%20woodland%20animals%20rabbits%20birds%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=555",
    P6: "https://image.pollinations.ai/prompt/soft%20dreamy%20watercolor%20painting%2C%20Maya%20brown%20pigtails%20walking%20away%20from%20forest%20towards%20cozy%20cottage%20house%20in%20distance%2C%20warm%20sunset%20colors%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=666"
  },
  NOAH: {
    P1: "https://image.pollinations.ai/prompt/3d%20render%20style%20pixar%20style%2C%20Noah%20cute%20boy%20with%20messy%20red%20hair%20and%20green%20eyes%20digging%20in%20wooden%20sandbox%2C%20holding%20glowing%20blue%20dinosaur%20bone%2C%20sunny%20day%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=101",
    P2: "https://image.pollinations.ai/prompt/3d%20render%20style%20pixar%20style%2C%20Noah%20red%20hair%20standing%20amazed%20in%20prehistoric%20jungle%20with%20giant%20ferns%20and%20ancient%20trees%2C%20sunlight%20beaming%20down%2C%20high%20detail%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=202",
    P3: "https://image.pollinations.ai/prompt/3d%20render%20style%20pixar%20style%2C%20Noah%20red%20hair%20looking%20at%20cute%20baby%20Triceratops%20emerging%20from%20jungle%20bushes%2C%20dinosaur%20looks%20sad%20and%20cute%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=303",
    P4: "https://image.pollinations.ai/prompt/3d%20render%20style%20pixar%20style%2C%20Noah%20red%20hair%20feeding%20a%20sandwich%20to%20baby%20Triceratops%2C%20they%20look%20happy%20and%20friendly%2C%20jungle%20background%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=404",
    P5: "https://image.pollinations.ai/prompt/3d%20render%20style%20pixar%20style%2C%20Noah%20red%20hair%20and%20baby%20dino%20walking%20towards%20giant%20mother%20Triceratops%20in%20distance%2C%20muddy%20footprints%20on%20ground%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=505",
    P6: "https://image.pollinations.ai/prompt/3d%20render%20style%20pixar%20style%2C%20Noah%20red%20hair%20back%20in%20modern%20sandbox%20in%20a%20park%2C%20smiling%20and%20holding%20blue%20bone%2C%20confident%20expression%2C%20masterpiece%2C%20best%20quality%2C%208k?width=1024&height=1024&nologo=true&seed=606"
  }
};

const STATIC_EXAMPLES: Project[] = [
  {
    id: 'ex1',
    status: 'COMPLETED',
    consentGiven: true,
    theme: Theme.SPACE,
    style: 'cartoon',
    title: "Leo's Space Adventure",
    isPurchased: true,
    characters: [{ id: 'c1', name: 'Leo', age: 6, gender: 'boy', hairColor: 'blonde', eyeColor: 'blue' }],
    coverImageUrl: ASSETS.LEO.P2,
    storyPages: [
      {
        pageNumber: 1,
        text: "Leo adjusted his shimmering silver helmet, his blonde curls bouncing with excitement. Tonight wasn't just any night; his cardboard box had transformed into the Star-Hopper 3000. 'All systems go!' he whispered, pressing a big red button drawn in crayon.",
        imagePrompt: "cute cartoon illustration of Leo, a young boy with curly blonde hair and blue eyes wearing a silver space helmet, sitting in a cardboard box spaceship in his bedroom, night time, cozy atmosphere",
        imageUrl: ASSETS.LEO.P1
      },
      {
        pageNumber: 2,
        text: "With a WHOOSH that sounded suspiciously like his dad sneezing, the room dissolved into twinkling starlight. Leo floated weightless, his blue eyes wide as he watched planets spin like colorful marbles outside his window.",
        imagePrompt: "cute cartoon illustration of Leo, a young boy with curly blonde hair, floating in zero gravity inside a spaceship, looking out the window at colorful planets, outer space background",
        imageUrl: ASSETS.LEO.P2
      },
      {
        pageNumber: 3,
        text: "Suddenly, a purple tentacle tapped on the glass. It was Blip, a friendly alien with three eyes and a wide, gummy smile. Blip pointed frantically towards a moon made entirely of cheese that was drifting away!",
        imagePrompt: "cute cartoon illustration of Leo (blonde hair) looking surprised as a cute three-eyed purple alien taps on the spaceship window, background shows space and stars",
        imageUrl: ASSETS.LEO.P3
      },
      {
        pageNumber: 4,
        text: "Leo steered the Star-Hopper with expert hands. 'Hang on, Blip!' he shouted. He deployed the grappling hook—which looked a lot like his yo-yo—and snagged the runaway moon just in time.",
        imagePrompt: "cute cartoon illustration of Leo (blonde hair) piloting the spaceship, using a joystick, outside view shows a yo-yo grappling hook catching a yellow moon made of cheese",
        imageUrl: ASSETS.LEO.P4
      },
      {
        pageNumber: 5,
        text: "Blip cheered and did a wiggly dance. As a thank you, the aliens shared a basket of moon-berries that tasted like fizzy pop. Leo waved goodbye as his ship turned back toward the blue marble of Earth.",
        imagePrompt: "cute cartoon illustration of Leo (blonde hair) waving goodbye to the purple alien Blip, Leo is holding a basket of glowing berries, earth visible in distance",
        imageUrl: ASSETS.LEO.P5
      },
      {
        pageNumber: 6,
        text: "The Star-Hopper landed softly on the rug. Leo crawled out, sleepy but happy. He snuggled into bed, dreaming of his next galactic mission.",
        imagePrompt: "cute cartoon illustration of Leo (blonde hair) sleeping peacefully in his bed, the cardboard box spaceship next to him, moonlight shines in through window",
        imageUrl: ASSETS.LEO.P6
      }
    ]
  },
  {
    id: 'ex2',
    status: 'COMPLETED',
    consentGiven: true,
    theme: Theme.FOREST,
    style: 'watercolor',
    title: "Maya's Magical Forest",
    isPurchased: true,
    characters: [{ id: 'c2', name: 'Maya', age: 5, gender: 'girl', hairColor: 'dark brown', eyeColor: 'brown' }],
    coverImageUrl: ASSETS.MAYA.P5,
    storyPages: [
      {
        pageNumber: 1,
        text: "Maya tiptoed through the garden gate, her dark brown pigtails bobbing in the breeze. The old oak tree at the edge of the woods seemed to be humming a low, ancient tune today.",
        imagePrompt: "soft watercolor painting of Maya, a little girl with dark brown pigtails and brown eyes, opening a wooden garden gate, lush green garden",
        imageUrl: ASSETS.MAYA.P1
      },
      {
        pageNumber: 2,
        text: "At the base of the tree, she found a tiny door carved into the bark. It was no bigger than her shoe! Maya knelt down, her brown eyes full of wonder.",
        imagePrompt: "soft watercolor painting of Maya (brown pigtails) kneeling at the base of a large oak tree, looking closely at a tiny magical wooden door carved in the bark",
        imageUrl: ASSETS.MAYA.P2
      },
      {
        pageNumber: 3,
        text: "The door creaked open, and out stepped a squirrel wearing a monocle. 'Late! I'm late for the acorn festival!' he squeaked, checking a pocket watch made of a sunflower seed.",
        imagePrompt: "soft watercolor painting of a cute squirrel wearing a monocle and holding a sunflower seed watch, standing next to Maya (brown pigtails), magical forest vibe",
        imageUrl: ASSETS.MAYA.P3
      },
      {
        pageNumber: 4,
        text: "Maya giggled. 'Can I help?' she asked. She scooped up the squirrel and ran through the forest, jumping over mossy logs and ducking under fern leaves.",
        imagePrompt: "soft watercolor painting of Maya (brown pigtails) running through a magical forest holding the squirrel, sunlight filtering through leaves, dynamic action",
        imageUrl: ASSETS.MAYA.P4
      },
      {
        pageNumber: 5,
        text: "They arrived at a clearing just as the fireflies began to light up. The squirrel hopped down and chattered his thanks. The forest animals cheered for Maya.",
        imagePrompt: "soft watercolor painting of Maya (brown pigtails) standing in a forest clearing surrounded by glowing fireflies and happy woodland animals like rabbits and birds",
        imageUrl: ASSETS.MAYA.P5
      },
      {
        pageNumber: 6,
        text: "Walking home, Maya felt the magic of the forest in her heart. She knew she'd always have friends among the trees.",
        imagePrompt: "soft watercolor painting of Maya (brown pigtails) walking away from the forest towards a cozy cottage house in the distance, warm sunset colors",
        imageUrl: ASSETS.MAYA.P6
      }
    ]
  },
  {
    id: 'ex3',
    status: 'COMPLETED',
    consentGiven: true,
    theme: Theme.DINOSAUR,
    style: '3d_render',
    title: "Noah & The Lost Bone",
    isPurchased: true,
    characters: [{ id: 'c3', name: 'Noah', age: 4, gender: 'boy', hairColor: 'red', eyeColor: 'green' }],
    coverImageUrl: ASSETS.NOAH.P2,
    storyPages: [
      {
        pageNumber: 1,
        text: "Noah was digging in the sandbox when his shovel hit something hard. CLINK! He brushed away the sand to reveal a glowing blue bone.",
        imagePrompt: "3d render style, pixar style, Noah, a cute boy with messy red hair and green eyes, digging in a wooden sandbox, holding a glowing blue dinosaur bone, sunny day",
        imageUrl: ASSETS.NOAH.P1
      },
      {
        pageNumber: 2,
        text: "As soon as he touched it, the playground melted away. Noah was standing in a lush jungle with giant ferns towering over his red hair.",
        imagePrompt: "3d render style, Noah (red hair) standing amazed in a prehistoric jungle with giant ferns and ancient trees, sunlight beaming down, high detail",
        imageUrl: ASSETS.NOAH.P2
      },
      {
        pageNumber: 3,
        text: "The ground shook. BOOM. BOOM. A baby Triceratops poked its head out from a bush. It looked lonely.",
        imagePrompt: "3d render style, Noah (red hair) looking at a cute baby Triceratops emerging from jungle bushes, the dinosaur looks sad and cute",
        imageUrl: ASSETS.NOAH.P3
      },
      {
        pageNumber: 4,
        text: "'Are you lost?' Noah asked gently. He shared his peanut butter sandwich with the dinosaur. They became instant friends.",
        imagePrompt: "3d render style, Noah (red hair) feeding a sandwich to the baby Triceratops, they look happy and friendly, jungle background",
        imageUrl: ASSETS.NOAH.P4
      },
      {
        pageNumber: 5,
        text: "Noah helped the baby dino find its mama by following the giant footprints in the mud. The mama dinosaur roared a happy thank you.",
        imagePrompt: "3d render style, Noah (red hair) and the baby dino walking towards a giant mother Triceratops in the distance, muddy footprints on the ground",
        imageUrl: ASSETS.NOAH.P5
      },
      {
        pageNumber: 6,
        text: "With a flash of light, Noah was back in his sandbox. He squeezed the blue bone in his pocket, knowing he was the greatest explorer of all time.",
        imagePrompt: "3d render style, Noah (red hair) back in the modern sandbox in a park, smiling and holding the blue bone, confident expression",
        imageUrl: ASSETS.NOAH.P6
      }
    ]
  }
];

const getPersistedExamples = (): Project[] => {
  if (typeof window === 'undefined') return [];
  try {
    const stored = localStorage.getItem('amazebook_saved_examples');
    return stored ? JSON.parse(stored) : [];
  } catch (e) {
    console.error('Error loading saved examples:', e);
    return [];
  }
};

export const EXAMPLE_PROJECTS: Project[] = [
  ...getPersistedExamples(),
  ...STATIC_EXAMPLES
];